

spring.datasource.url=${DataSourceURL}
spring.datasource.username=${B_P_User}
spring.datasource.password=${B_P_Password}

server.port=8085
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
bezkoder.app.jwtSecret= ${B_P_JWT}
bezkoder.app.jwtExpirationMs=86400000


logging.level.root=INFO

# Optionally: limit file size and rotate
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

azure.storage.connection-string=${B_P_Azure_con_string}
azure.storage.positions.container-name=posimgs
azure.storage.positions.container-url=https://bopositionsimg.blob.core.windows.net/posimgs
