spring.datasource.url=jdbc:mysql://147.93.127.39:3306/WeddingDB
spring.datasource.username=admin
spring.datasource.password=Timoha2004!

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

# App Properties
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000


logging.level.root=INFO
logging.file.name=logs/boparty-logs.log
# Optionally: limit file size and rotate
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
